### ISSUE TITLE
Where is Flash Attention used in the finetuning process?

### ISSUE THREAD

**Issue by nahidalam** [ayulockin/neurips-llm-efficiency-challenge#1]
I see you are installing Flash Attention. But I am not sure if you are using it for finetuning process. Maybe I am missing something? 

Please suggest

**Comment by ayulockin** [comment]
Flash attention is used here: https://github.com/ayulockin/lit-gpt/blob/b6829289f977e65c3588bbb28737986fe38f8ec1/lit_gpt/model.py#L259C51-L259C51
