### ISSUE TITLE
Error building flash attention

### ISSUE THREAD

**Issue by nahidalam** [ayulockin/neurips-llm-efficiency-challenge#3]
I have cuda 11.5 on an ubuntu machine. When I do `MAX_JOBS=8 pip install flash-attn --no-build-isolation`, I get error
```
RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for flash-attn
  Running setup.py clean for flash-attn
Failed to build flash-attn
ERROR: Could not build wheels for flash-attn, which is required to install pyproject.toml-based projects
```

I made sure g++ is installed

**Comment by ayulockin** [comment]
How much RAM do you have? I tested MAX_JOBS=8 with 85 GB of RAM (A100 40GB variant).

**Comment by ayulockin** [comment]
I went through this [issue](https://github.com/Dao-AILab/flash-attention/issues/224) and figured that g++ and CUDA got dependence. If your g++ is not compatible, flash attention might fail. For CUDA 11.5 I think max supported GCC (equivalent to g++ imo) for 11.5 CUDA is 11. You might find this [useful](https://stackoverflow.com/a/46380601/8663152).

**Comment by nahidalam** [comment]
Built cuda toolkit 11.8 inside the conda environment. That at least solves the flash attention installation problem
```
conda install -c "nvidia/label/cuda-11.8.0" cuda-toolkit
```
