### ISSUE TITLE
Set up submission pipeline without sudo 

### ISSUE THREAD

**Issue by tranxuantuyen** [ayulockin/neurips-llm-efficiency-challenge#6]
Hi, I am not able to run sudo on the sever machine. Do you know any other ways to make the Docker submission. Thanks

**Comment by ayulockin** [comment]
Not really. I will investigate though.

**Comment by tranxuantuyen** [comment]
Thank you. But is it true that I can still evaluate on HELM without the docker image, right? 

I followed your instructions successfully until done evaluation on EluetherAI LM Eval Harness. I am struggling on how to evaluate on HELM. After running `helm-run --conf-paths run_specs.conf --suite v1 --max-eval-instances 1000`, I got the error

```
 File "/home/s222126678/Documents/meccano/project/helm/src/helm/proxy/models.py", line 701, in get_model
    raise ValueError(f"No model with name: {model_name}")
ValueError: No model with name: neurips/local
```

I am a bit confuse where is the `neurips/local` come from. How can I specify the model to evaluate as done in EluetherAI LM Eval Harness. Could you give me some suggestions, many thanks

I already have the HTTP client by running `uvicorn main_submission:app` 

![image](https://github.com/ayulockin/neurips-llm-efficiency-challenge/assets/29355083/b6e8a66f-f3d6-486a-9e71-8cf7a34be33c)

**Comment by tranxuantuyen** [comment]
Hi, I has figured out the reason, this because the HELM repo has updated. I converted it to the previous version then works. Thanks

**Comment by tranxuantuyen** [comment]
Hi, I has figured out the reason, this because the HELM repo has updated. I converted it to the previous version then works. Thanks
